### ISSUE TITLE
Available internally

### ISSUE THREAD

**Issue by xunafay** [alvarium-hex/melipona#5]
```[tasklist]
### Tasks
- [ ] https://github.com/alvarium-hex/melipona/issues/9
- [ ] https://github.com/alvarium-hex/melipona/issues/7
- [ ] https://github.com/alvarium-hex/melipona/issues/8
```
